version: "3"

services:
  db:
    image: postgres:15.1
    container_name: database
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: task1
    ports:
      - 5432:5432
    networks:
      - python_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "docker_app"]
      interval: 5s
      timeout: 5s
      retries: 3

  python:
    image: egor_test
    volumes:
      - .:/Innowise_Python_Task1
    networks:
      - python_net
    depends_on:
      db:
        condition: service_healthy

networks:
  python_net:
    name: python_net
