version: "3"

services:
  db:
    image: postgres:15.1
    container_name: database
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: task1
    networks:
      - python_net

  python:
    image: python:3.10.6 #свой имедж
    volumes:
      -python_task:app/Innowise_Python_Task1/source/output_data
    networks:
      - python_net 


volumes:
  python_task: ./Innowise_Python_Task1/source/output_data
    
networks:
  python_net:
    name: python_net
