name: CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start Docker daemon
      run: |
        sudo systemctl start docker
    - name: Run Postgres Database within Docker
      run: |
        docker run --rm -d -p 5444:5444 -e POSTGRES_PASSWORD=test \
          -e POSTGRES_USER=test \
          -e POSTGRES_DB=test \
          --name pg_db postgres:latest
  test:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
        pip install -r requirements.txt
    - name: Run tests inside Docker container
      run: |
        pytest --cov-report term-missing --cov=.
  pre-commit:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    - name: Install pre-commit
      run: |
        pip install -r requirements-pre-commit.txt
    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files --show-diff-on-failure
