name: CI

on: [push]

jobs:
  docker:
    runs_on: ubuntu-latest
    name: Install Docker
    run: |
      apt-get update && apt-get install -y docker.io
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest --cov-report term-missing --cov=.
  pre-commit:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Install pre-commit
      run: |
        pip install -r requirements-pre-commit.txt
    - name: Run pre-commit checks
      run: |
        pre-commit run --all-files --show-diff-on-failure
